language: android
jdk:
  - oraclejdk8

env:
  global:
    - ANDROID_ABI=arm64-v8a
    - ANDROID_TAG=google_apis
    - EMULATOR_API_LEVEL=25
    - ADB_INSTALL_TIMEOUT=8

android:
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-28.0.3
    - android-27
    - sys-img-$ANDROID_ABI-$ANDROID_TAG-$EMULATOR_API_LEVEL

before_install:
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;28.0.3"

before_script:
  - echo no | android create avd --force -n test -t "android-"$EMULATOR_API_LEVEL --abi $ANDROID_ABI --tag $ANDROID_TAG
  - emulator -avd test -no-skin -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

jobs:
  include:
    - stage: build
      script: ./gradlew clean assembleDebug
    - stage: unit-test
      script: ./gradlew clean test
    - stage: android-test
      script: ./gradlew clean build connectedAndroidTest
