language: android
jdk:
  - oraclejdk8

android:
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-28.0.3
    - android-27
before_install:
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;28.0.3"

jobs:
  include:
    - stage: build
      script: ./gradlew clean assembleDebug
    - stage: unit-test
      script: ./gradlew clean test
    - stage: android-test
      script: ./gradlew clean build connectedAndroidTest
